
name: Test Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2.6.0
    
    - name: Setup Python 3.8
      uses: actions/setup-python@v4.4.0
      with:
        python-version: '3.8'

    - name: Test Bot
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt
        pip install pytest
        pip install nonebug pytest-asyncio
        python ./bottest.py
