# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
    - uses: actions/checkout@v2.6.0
    
    - name: Setup Python 3.8
      uses: actions/setup-python@v4.4.0
      with:
        python-version: 3.8.10

    - name: Grant execute permission for gradlew
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt
        python ./boot.py
